{
 "title": "ISS2SaVe Dashboard",
 "time": { "from": "2022-07-03T19:20:12.193Z", "to": "2022-07-18T08:36:11.675Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "LATEST_EXPERIMENT", "label": "Auswahl Experiment", "query": "SELECT ID FROM experiment" }
  ]
 },
 "panels": [
  {
   "title": "Scenario Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT title, description FROM experiment  WHERE id = '$LATEST_EXPERIMENT'"
    }
   ]
  },
  {
   "title": "Einsatzortauslastung",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"time\",\n Round((avg(current_admin* 100/NULLIF(required_admin,0)) +\n    avg(current_easy* 100/NULLIF(required_easy,0))+\n\t  avg(current_medium* 100/NULLIF(required_medium,0))+\n\t    avg(current_heavy* 100/NULLIF(required_heavy,0)))/4,0)\n as utilization,\n name,\n ST_X(ST_Transform ( ST_GeomFromWKB(location), 4326)) AS longitude,\nST_Y(ST_Transform ( ST_GeomFromWKB(location), 4326)) AS latitude\n FROM operating_site_history as os \n  WHERE experiment_id = '$LATEST_EXPERIMENT'\n GROUP BY time, location,name ORDER BY time "
    }
   ]
  },
  {
   "title": "Übersicht Änderungen Events/Einsatzorte",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  name AS \"Bezeichnung\",\n  impact AS \"Impact\",\n  information AS \"Information\",\n  media AS \"Media\",\n  precipitation AS \"Precipitation\",\n  temperature AS \"Temperature\",\n  threat AS \"Threat\",\n  required_admin AS \"Admin\",\n  required_easy AS \"Easy\",\n    required_medium AS \"Medium\",\n  required_heavy AS \"Heavy\"\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY name,impact,information,media,precipitation,threat,temperature,required_admin,required_easy,required_medium,required_heavy\nORDER BY name"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Übersicht Helfende",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval),\n  avg(totaldaysworked) AS \"Tage (Ø)\",\n  sum(totalhourshelped) AS \"Helferstunden (∑)\",\n  avg(totalhourshelped) / NULLIF(avg(totaldaysworked),0) AS \"Stunden (Ø)\"\nFROM spontaneous_volunteers\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Zurückweisungen (Ø)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select totalnumberofrejects, timestamp as time\nfrom spontaneous_volunteers\nwhere experiment_id = '$LATEST_EXPERIMENT'\ngroup by time,totalnumberofrejects"
    }
   ]
  },
  {
   "title": "Spontanhelferbewegungen",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": " SELECT timestamp as \"time\", \n id,\n ST_X(ST_Transform ( ST_GeomFromWKB(current_location), 4326)) AS \"Longitude\",\nST_Y(ST_Transform ( ST_GeomFromWKB(current_location), 4326)) AS \"Latitude\"\n FROM spontaneous_volunteers as sv \n WHERE experiment_id = '$LATEST_EXPERIMENT'\n GROUP BY timestamp,current_location,id ORDER BY timestamp desc LIMIT 20000"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Durchschnittliche Auslastung aller Einsatzorte (in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  timestamp as time,\n  name as metric,\n  Round((avg(current_admin* 100/NULLIF(required_admin,0)) +\n    avg(current_easy* 100/NULLIF(required_easy,0))+\n\t  avg(current_medium* 100/NULLIF(required_medium,0))+\n\t    avg(current_heavy* 100/NULLIF(required_heavy,0)))/4,0)\n\t\t\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY time, name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Durchschnittliche Auslastung der Einsatzorte",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND((avg(current_admin* 100/NULLIF(required_admin,0)) +\n    avg(current_easy* 100/NULLIF(required_easy,0))+\n\t  avg(current_medium* 100/NULLIF(required_medium,0))+\n\t    avg(current_heavy* 100/NULLIF(required_heavy,0)))/4,0)\n\t\t,\nCASE WHEN TO_TIMESTAMP(timestamp / 1000)::time <  '06:00' THEN 'Nacht'\n            WHEN TO_TIMESTAMP(timestamp / 1000)::time >= '22:00' THEN 'Nacht'\n            ELSE 'Tag' END AS daytime\nFROM  operating_site_history\nWHERE experiment_id =  '$LATEST_EXPERIMENT'\nGroup by daytime\n"
    },
    {
     "rawSql": "SELECT\n  ROUND((avg(current_admin* 100/NULLIF(required_admin,0)) +\n    avg(current_easy* 100/NULLIF(required_easy,0))+\n\t  avg(current_medium* 100/NULLIF(required_medium,0))+\n\t    avg(current_heavy* 100/NULLIF(required_heavy,0)))/4,0) as \"Gesamt\"\n\nFROM  operating_site_history\nWHERE experiment_id =  '$LATEST_EXPERIMENT'\n\n"
    }
   ]
  },
  {
   "title": "Absolute Anzahl an Zurückweisungen an Einsatzorten",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(\"timestamp\",$__interval),\n  name AS metric,\n  sum(current_rejects) AS \"current_rejects\"\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Auslastung für Easy-Tasks (in %)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  timestamp as time,\n  name as metric,\n  avg(current_easy* 100/NULLIF(required_easy,0))\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY time, name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Auslastung für Admin-Tasks (in %)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  timestamp as time,\n  name as metric,\n  avg(current_admin* 100/NULLIF(required_admin,0))\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY time, name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Auslastung für Medium-Tasks (in %)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  timestamp as time,\n  name as metric,\n  avg(current_medium* 100/NULLIF(required_medium,0))\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY time, name\nORDER BY time"
    }
   ]
  },
  {
   "title": "Auslastung für Heavy-Tasks (in %)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  timestamp as time,\n  name as metric,\n  avg(current_heavy* 100/NULLIF(required_heavy,0))\nFROM operating_site_history\n WHERE experiment_id = '$LATEST_EXPERIMENT'\nGROUP BY time, name\nORDER BY time"
    }
   ]
  }
 ]
}